### ISSUE TITLE
[Smarties_sorter] Connecteur capteur de couleur

### ISSUE THREAD

**Issue by Fabien-B** [ENACRobotique/elec#4]
SDA et SCL sont inversés entre le connecteur et le brochage du capteur.
Suggestion : 
Faire un connecteur 5 broches dans l'odre "5V, GND, SDA, SCL, LED".
Ainsi, les 4 premières broches respectent le standard du club, et on économise de la place par rapport à un connecteur à 5 broches.

Autre suggestion : ne pas utiliser la broche RX (ni TX) de l'atmega, ça peut toujours servir.
Il y a plein de roches de libres, autant en profiter !

**Comment by guilhembn** [comment]
Schématic ok 1990f71

**Comment by Fabien-B** [comment]
Board ok : 08d478a
