### ISSUE TITLE
[Smarties_sorter] Commande du moteur

### ISSUE THREAD

**Issue by Fabien-B** [ENACRobotique/elec#5]
supprimer la résistance entre PD5 et la gate du mosfet, et en ajouter une de 10Kohms environ (on n'est pas à une vache près) entre la gate en la masse.
La résistance rappelle ainsi le potentiel à la masse lorsque l'état de la broche est incertain, empêchant le moteur de tourner.

**Comment by guilhembn** [comment]
Schematic solved in cbb99e2

**Comment by Fabien-B** [comment]
Board ok : 08d478a
