### ISSUE TITLE
[Smarties_sorter] Ajout d'un connecteur série

### ISSUE THREAD

**Issue by Fabien-B** [ENACRobotique/elec#6]
Ajouter un connecteur pour le RX/TX (avec la norme du club : 5V, GND, TX, RX) permettrait de pouvoir s'interfacer avec d'autres systèmes si on veut faire évoluer le projet.
Par exemple on pourrait le connecter à l'afficheur de caisse pour afficher des stats sur les smarties triés. (Y a t'il le même nombres de smarties de chaque couleur dans les paquets ? le nombre de smarties par paquet ?  l'écart type ?)

**Comment by guilhembn** [comment]
Schematic ok : beed567

**Comment by Fabien-B** [comment]
Board ok : 08d478a
