### ISSUE TITLE
[Smarties_sorter] lissage de la tension moteur

### ISSUE THREAD

**Issue by Fabien-B** [ENACRobotique/elec#7]
C'est pas obligatoire (du tout), mais peut être pourrait-on ajouter un condo aux bornes du moteur ?
Si on utilise un petit moteur, peut être qu'il aura un peu mal avec le 5 ou 12V (ou pas)

**Comment by guilhembn** [comment]
Schematic ok : 35db900

**Comment by Fabien-B** [comment]
Board ok : 08d478a
